name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
jobs:
  lint:
    strategy:
      matrix:
        deno-version: [v1.x]
        os: [ubuntu-latest, macos-latest]
    name: deno lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: run lint
        run: deno lint
  test:
    strategy:
      matrix:
        runner:
          - macos-latest
          - ubuntu-latest
        version:
          - "1.x"
        host_version:
          - vim: "v8.2.3081"
            nvim: "v0.5.0"
    runs-on: ${{ matrix.runner }}
    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: "${{ matrix.version }}"
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: "${{ matrix.host_version.vim }}"
        if: matrix.host_version.vim != ''
      - uses: rhysd/action-setup-vim@v1
        id: nvim
        with:
          neovim: true
          version: "${{ matrix.host_version.nvim }}"
        if: matrix.host_version.nvim != ''
      - name: Install germanium
        run: |
          case $( uname -s ) in
            Linux)
              curl -L "https://github.com/matsuyoshi30/germanium/releases/download/v1.2.2/germanium_1.2.2_linux_x86_64.tar.gz" -o /tmp/germanium.tar.gz
              ;;
            Darwin)
              curl -L "https://github.com/matsuyoshi30/germanium/releases/download/v1.2.2/germanium_1.2.2_darwin_x86_64.tar.gz" -o /tmp/germanium.tar.gz
              ;;
          esac
          tar xvzf /tmp/germanium.tar.gz -C /usr/local/bin/
          chmod 777 /usr/local/bin/germanium
      - name: Clone denops
        id: denops
        run: |
          git clone https://github.com/vim-denops/denops.vim $HOME/denops.vim
          echo "::set-output name=path::$HOME/denops.vim"
      - name: Test
        run: |
          make test
        env:
          DENOPS_TEST_VIM: ${{ steps.vim.outputs.executable }}
          DENOPS_TEST_NVIM: ${{ steps.nvim.outputs.executable }}
          DENOPS_PATH: ${{ steps.denops.outputs.path }}
        timeout-minutes: 5
